language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - node_modules
script:
  - npm run fix-code-CI
  - npm run fix-styles-CI
  - npm run lint
  - npm test
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master
